# Generated by Django 2.0.5 on 2018-08-26 21:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180826_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.AddField(
            model_name='comments',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 26, 21, 27, 17, 858672, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 26, 21, 27, 17, 858201, tzinfo=utc)),
        ),
    ]
