# Generated by Django 2.0.5 on 2018-08-26 21:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180826_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='create_date',
        ),
        migrations.AddField(
            model_name='comments',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 26, 21, 38, 23, 626373, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 26, 21, 38, 23, 625854, tzinfo=utc)),
        ),
    ]
